- hosts: all
  gather_facts: yes
  vars:
    puppet_download: http://apt.puppetlabs.com/puppetlabs-release-pc1
    puppet_name: puppetlabes-release.deb
    download_folder: /var/tmp
    puppet_archive: "{{download_folder}}/{{puppet_name}}.deb"

  tasks:
  - name: Update apt-cache [apt]
    apt: "update_cache=yes"
    become: yes
    when: ansible_os_family  == "Debian"
  - name: Download the Puppet repo package
    get_url: url={{ puppet_download }}-{{ ansible_distribution_release }}.deb dest={{ puppet_archive }}
    when: ansible_os_family  == "Debian"
  - name: Install the puppet repo package [apt]
    apt: "deb={{ puppet_archive }}"
    become: yes
    when: ansible_os_family  == "Debian"
  - name: Install the puppet repo package [yum]
    yum: "name=http://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm"
    become: yes
    when: ansible_os_family  == "RedHat" or ansible_os_family  == "Centos"
  - name: Update apt-cache
    apt: "update_cache=yes"
    become: yes
    when: ansible_os_family  == "Debian"
  - name: Install all the required packaes for a puppetmaster [apt]
    apt: "pkg={{item}} state=present"
    become: yes
    with_items: [
      "puppetserver",
      "puppetdb",
      "puppet-agent",
      "puppetdb-termini",
      "git"
      ]
    when: ansible_os_family  == "Debian"
  - name: Install all the required packaes for a puppetmaster [yum]
    yum: "name={{item}} state=present"
    become: yes
    with_items: [
      "puppetserver",
      "puppetdb",
      "puppet-agent",
      "puppetdb-termini",
      "git"
      ]
    when: ansible_os_family  == "RedHat" or ansible_os_family  == "Centos"
#  - name: install r10k
#    command: gem install --verbose r10k creates="/usr/bin/r10k"
#    become: yes
  - name: Change Java heap size
    command: sed -i 's/-Xms2g -Xmx2g/-Xms1g -Xmx1g/g /etc/default/puppetserver'
    become: yes
  - name: Start the puppetmaster service
    service: "name=puppetserver state=started"
    become: yes
  #- name: "puppetmaster must have a /etc/hosts entry"
    #lineinfile: dest=/etc/hosts line="127.0.0.1 puppet puppetmaster" state=present
  - name: Set puppet to start on boot
    command: /opt/puppetlabs/bin/puppet resource service puppet ensure=running enable=true
  - name: puppet agent --test
    command: /opt/puppetlabs/bin/puppet agent --test --server {{ansible_fqdn}} creates="/var/lib/puppet/ssl/certs/{{ ansible_fqdn }}"
    become: yes
  - name: puppetdb ssl-setup
    command: puppetdb ssl-setup creates="/etc/puppetdb/ssl"
    become: yes
  - name: Install default hiera.conf
    template: src=hiera.conf.j2 dest=/etc/puppet/hiera.conf owner=root group=root mode=0644
    become: yes
  - name: Install default puppet.conf
    template: src=puppet.conf.j2 dest=/etc/puppet/puppet.conf owner=root group=root mode=0644
    become: yes
  - name: Install default puppetdb.conf
    template: src=puppetdb.conf.j2 dest=/etc/puppet/puppetdb.conf owner=root group=root mode=0644
    become: yes
  - name: Install default routes.yaml
    template: src=routes.yaml.j2 dest=/etc/puppet/routes.yaml owner=root group=root mode=0644
    become: yes
  - name: Install default r10k.yaml
    template: src=r10k.yaml.j2 dest=/etc/r10k.yaml owner=root group=root mode=0644
    become: yes
  - name: r10k deploy
    command: r10k deploy environment creates="/etc/puppet/environments/master"
    become: yes
  - name: install puppet-lint
    gem: name=puppet-lint
    become: yes
  - name: Start all the services.
    service: "name={{item}} state=restarted"
    become: yes
    with_items: [
      "puppetserver",
      "puppetdb",
    ]
